import { Color, View } from "@nativescript/core";
export declare class RippleHelperCommon {
    protected static DEFAULT_RIPPLE_ALPHA: number;
    protected tnsView: WeakRef<View>;
    protected effectiveColor: Color;
    protected _rippleColor: string | Color;
    protected _rippleColorAlpha: number | null | undefined;
    protected _enabled: boolean;
    protected rippleApplied: boolean;
    protected _rippleLayer: "background" | "foreground" | "auto";
    protected initialized: boolean;
    get enabled(): boolean;
    set enabled(v: boolean);
    get rippleLayer(): "background" | "foreground" | "auto";
    set rippleLayer(layer: "background" | "foreground" | "auto");
    get color(): string | Color;
    set color(v: string | Color);
    set alpha(v: number | null | undefined);
    get alpha(): number | null | undefined;
    constructor(tnsView: View);
    init(): void;
    dispose(): void;
    refreshRippleState(): void;
    protected apply(): boolean;
    protected remove(): boolean;
    protected invalidateColor(): void;
    protected refreshRippleColor(): void;
    protected onLoaded(): void;
    protected onUnloaded(): void;
    private setEffectiveColor;
    private bindEvents;
}
